### ISSUE TITLE
working directory is being ignored

### ISSUE THREAD

**Issue by jorgecoca** [VeryGoodOpenSource/very_good_coverage#35]
**Describe the bug**
When you declare a `working-directory` for your action, all the paths should be relative to that directory, and not to the root of the project. 

**Expected behavior**

```yaml
jobs:
  build:
    defaults:
      run:
        working-directory: test/path
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: ./coverage/lcov.info
```

The absolute value of `path` should be `test/path/coverage/lcov.info`, and not just `./coverage/lcov.info`.

**Comment by albertodev01** [comment]
I have just ran into this issue as well with this setup:

```yaml
  verify_equation_flutter_example:
    name: Equations Flutter example - CI action
    needs: [verify_equation_package]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    defaults:
      run:
        working-directory: example/flutter_example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Installing the dependencies
        run: flutter pub get

      - name: Making sure the package is formatted
        run: flutter format --set-exit-if-changed .

      - name: Making sure that there are no analysis warnings or errors
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Runing unit and widget tests
        run: flutter test --update-goldens --coverage

      - name: Making sure that code coverage is at least 90
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:          
          min_coverage: 90
```

All of this is **almost** good because, in order to make the coverage tool work, I need to explicitly set the path:

```yaml
      - name: Making sure that code coverage is at least 90
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:          
          path: example/flutter_example/coverage/lcov.info
          min_coverage: 90
```

This is not a big deal but it'd be convenient if the path were automatically "adjusted" to the relative one specified by `working-difectory`
